name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies for backend
        run: |
          cd backend
          npm install

      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Run tests for backend
        run: |
          cd backend
          npm test
        continue-on-error: true

      - name: Run tests for frontend
        run: |
          cd frontend
          npm test -- --passWithNoTests
        continue-on-error: true

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          scp -i ${{ secrets.EC2_KEY_PATH }} -r . ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/SNS-APP
          ssh -i ${{ secrets.EC2_KEY_PATH }} ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/SNS-APP
            npm install
            pm2 restart all
          EOF
