name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy to EC2
        env:
          EC2_KEY_PATH: ${{ secrets.EC2_KEY_PATH }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.EC2_KEY_PATH }}" > /home/runner/.ssh/your-key.pem
          chmod 400 /home/runner/.ssh/your-key.pem
          scp -i /home/runner/.ssh/your-key.pem -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/SNS-APP

      - name: Restart application on EC2
        env:
          EC2_KEY_PATH: ${{ secrets.EC2_KEY_PATH }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i /home/runner/.ssh/your-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pm2 restart all"
