name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install
          cd ..

      - name: Run tests
        run: |
          cd backend
          npm test
          cd ../frontend
          npm test
          cd ..

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_KEY_PATH: ${{ secrets.EC2_KEY_PATH }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $EC2_KEY_PATH $EC2_USER@$EC2_HOST 'bash -s' << 'EOF'
            cd /home/ec2-user/SNS-APP
            git pull origin main
            pm2 restart all
          EOF
